sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: gGhi14esVECq75jsNiKkupWTge1jGUEAOQObATAFyKmbStrEHZDKXCx34mfcMMUmkx255x5wLBLuPbKobBypIIF43Ok7F8+c29/jZLjYlF7EjKunxZ4Ym3L6/63cekAaog/AF69dPxHUIi+EMrdjFl4yKfOiqRsGaHy2DY7Ove5QPU6H7hReNg03d7M1G+axcC89gp18GUwG7FDdex44eN0YECFt9M68q+2uIwTCuhprSunRMseio9cc9bXJe/6EjUPoji4sPNN/Pc2W4S3ost9p61z0bSvWNamWj9mFelYF06xmwyhew68EE6fS4QiUKILgSEfVmtA+EiBWEDAdkPisM3l5Z+JY/blDcSq7uGQgr3r0yd88StS85A3gDuGNDoIXE1HofUpFQ6n5XLM2affnB6fNjDRGPsfIjuTLW8+QaBOQ1sPlM6ujs2FG7MMKtX6b4cbTnMoC2IKsJsqbSDjyRabXA7LBK0wfdbH0LC7oJ0+Pz5tRYBfXP5seuG8Y4aXPTRWco+8OWBmKpngCbS/aF20RYHUgrzokzGGyt2CVXJkzn6eYoHhtL+u8StUtwqqt7qcqP+y2xAOgnAWFHRKLD0bVtYrykxyMUsjg4HhSkOEexAmiOKkkCf3veAtnzlFJHE/4ZLIIMMnYCMALaB5uCxrH7kU6lwTbwNDu/ZU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Love-of-Ulrich-Nebendahl_870
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy